ARG BASE_IMAGE=centos
ARG CENTOS_VERSION=latest
FROM ${BASE_IMAGE}:${CENTOS_VERSION}
LABEL org.label-schema.schema-version="1.0.0-demo" \
    maintainer="anish2good@yahoo.co.in" \
    org.label-schema.vcs-description="Centos7 mono" \
    org.label-schema.docker.cmd="docker exec " \
    image-size="71.6MB" \
    ram-usage="13.2MB to 70MB" \
    cpu-usage="Low"


COPY mono-centos7-stable.repo /etc/yum.repos.d/
COPY sheet.exe /usr/bin/
RUN yum -y update  && \
    yum -y install mono-devel && \
    yum -y install java