FROM mysql:5.6


LABEL org.label-schema.schema-version="1.0.0-demo" \
    maintainer="anish2good@yahoo.co.in" \
    org.label-schema.vcs-description="0cloud.com mysql latest Base Image with 0.0.0.0 Bind address" \
    org.label-schema.docker.cmd="docker run   -p 3306:3306 -e MYSQL_ROOT_PASSWORD=test   anishnath/mysql:5.6" \
    image-size="71.6MB" \
    ram-usage="13.2MB to 70MB" \
    cpu-usage="Low"


COPY my.cnf /etc/mysql/